# Node js 환경에서 빌드한다
FROM node:20-alpine as build
WORKDIR /app

# packge.json등을 복사해서 의존성 설치
COPY package*.json ./
RUN npm install

# 소스 파일들을 복사해서 빌드
COPY . .
RUN npm run build

# Nginx를 사용해 정적 파일 서빙
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# Nginx에서 사용할 포트 설정
EXPOSE 80

# Nginx를 실행 
CMD ["nginx", "-g", "daemon off;"]