# server port config
server:
  port: 8080  # server port

file:
  upload-dir: C:\uploads\profile-image
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # db config
  jwt:
    secret: vmfhaltmskdlstkfkdfdfkgfjsjdfgjsghewkwenbfehfdjhckdkdfjfsfdhjsfduh
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver         # ???? db driver
#    url: jdbc:mysql://host.docker.internal:3306/todo               # db url
    url: jdbc:mysql://localhost:3306/todo               # db url
    username: root                    # db username
    password: root                     # db password
  devtools:
    restart:
      enabled: false # auto restart option enabled


  # jpa config
  jpa:
    hibernate:
      ddl-auto: none      # DDL ???? ????
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect